Repository uasal/acronyms, pull requests merged in 2025-01, with the labels that each got.

#6 merge Develop
  README.md
  combined-acronyms.md
  combined_acronyms.tex
  compile-test.sh
  compile-test.tex
  gitinfo2-hook.sh
  glossaries.tex
Labels: documentation

#8 update: main with develop
  .github/workflows/md-workflow.yml
  combined_acronyms.tex
  compile-test.tex
  glossaries.tex
Labels: documentation, enhancement

#9 U/sfrinaldi/ci-fix-output
  .github/workflows/md-workflow.yml
  .gitignore
  compile-test.acn
  compile-test.acr
  compile-test.alg
  compile-test.aux
  compile-test.glg
  compile-test.glo
  compile-test.gls
  compile-test.ist
  compile-test.log
  compile-test.out
  compile-test.pdf
  compile-test.term-glg
  compile-test.term-glo
  compile-test.term-gls
  compile-test.toc
Labels: bug, documentation
